### ISSUE TITLE
samples please

### ISSUE THREAD

**Issue by uxcourt** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#35] opened 2020-03-31 01:37 UTC
Using Office365Users.UserProfile errors out in PowerApps stating the method. Invalid number of arguments: received 2, expected 1. This documentation states that the UserProfile call supports two parameters: userId and $select.

Samples of how to use UserProfile in a PowerApp connection would probably show me how I'm writing it incorrectly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8635712-d5a2-e58a-301f-cf849f2cf2e4
* Version Independent ID: 4cfdd73e-f074-0446-2aee-2dd013a8b30f
* Content: [Office 365 Users - Connectors](https://docs.microsoft.com/en-us/connectors/office365users/#feedback)
* Content Source: [docs/office365users/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/office365users/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment] 2020-04-29 23:28
Thank you for your feedback. This is now under review and no further action is required at this time.

**Comment by v-aangie** [comment] 2021-08-16 17:55
@uxcourt - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by v-aangie** 2021-08-16 17:55 UTC
Labels: under-review, open-for-too-long
