### ISSUE TITLE
Regarding Throttling Limits

### ISSUE THREAD

**Issue by DiptiC-InsightRun** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#55] opened 2020-04-14 14:19 UTC
Hello,

We have a PowerApps App connected with Excel file having less than 2000 records. This app displays a single record from the Excel file that the user has to update.

In the above scenario, If throttling limit for Excel Online connector is "API calls per connection" == 20, Does it mean, 20 users can work with this app and update data in Excel file simultaneously OR for PowerApps, Is there any different limitation for concurrent user access?

Also, How do we verify the number of API calls occurring in this App with Excel Online connector?

Thanks and Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63dd2d5e-d90f-4654-c406-256e3e680e6d
* Version Independent ID: f2cd384b-2690-393d-3058-a363523f7d62
* Content: [Excel Online (Business) - Connectors](https://docs.microsoft.com/en-us/connectors/excelonlinebusiness/?source=docs#limits)
* Content Source: [docs/excelonlinebusiness/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/excelonlinebusiness/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment] 2021-08-18 20:52
@DiptiC-InsightRun - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed** 2021-08-18 21:18 UTC
Labels: open-for-too-long
