### ISSUE TITLE
Is Data Lake Gen2 supported

### ISSUE THREAD

**Issue by mydiemho** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#163] opened 2020-07-24 20:30 UTC
It is not clear if Data Lake Gen2 is supported as the doc hasn't been updated for 2 years.

```
To use this integration, you will need an Azure Data Lake Storage Gen1 account
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64c26b3c-6338-35c1-05c8-2113fafd7ad6
* Version Independent ID: 4765e9e0-d187-5b9f-0df6-f6d92e93aa05
* Content: [Azure Data Lake - Connectors](https://docs.microsoft.com/en-us/connectors/azuredatalake/)
* Content Source: [docs/AzureDataLake/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/AzureDataLake/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment] 2021-08-19 22:11
@mydiemho - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed by v-aangie** 2021-08-19 22:11 UTC
Labels: doc-request, open-for-too-long
