### ISSUE TITLE
Add requirement to install required TSL/SSL certificates for authenticating between MySQL connector to on-premises MySQL Server

### ISSUE THREAD

**Issue by ecfan** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#103] opened 2020-05-18 18:58 UTC
Requesting doc improvements for MySQL connector that describe and/or emphasize the requirement to install required TSL/SSL certificates for authenticating requests from the MySQL connector to the on-premises MySQL Server through the on-premises data gateway.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0427dc6f-a63d-2bcb-b141-290335f47671
* Version Independent ID: 129d5c5a-2018-d8a6-e0ff-488f48aa22f8
* Content: [MySQL - Connectors](https://docs.microsoft.com/en-us/connectors/mysql/)
* Content Source: [docs/MySql/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/MySql/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment] 2021-08-19 18:55
@ecfan - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 18:55 UTC
Labels: doc-request, open-for-too-long
