### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Jad0r0** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#27] opened 2020-03-17 09:21 UTC
I am trying to work out what field I need to put into "File Content", this page doesnt really explain which of the many fields is supposed to go in there

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96687738-3384-ee5c-9587-26e282cc3fc5
* Version Independent ID: a2069780-474f-8d95-53da-196afc0c6867
* Content: [Docparser - Connectors](https://docs.microsoft.com/en-us/connectors/docparser/#feedback)
* Content Source: [docs/docparser/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/docparser/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment] 2020-03-21 22:39
Thank you for your feedback. This is now under review and no further action is required at this time.

**Comment by v-aangie** [comment] 2021-08-16 17:43
@Jad0r0 - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by v-aangie** 2021-08-16 17:43 UTC
Labels: documentation, under-review, open-for-too-long
