### ISSUE TITLE
API Key authentication using on-premises data gateway

### ISSUE THREAD

**Issue by marcindabrowski** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#44] opened 2020-04-06 08:08 UTC
It is nowhere documented, but in UI when I check "Connect via on-premises data gateway" API Key becomes unavailable in the Security tab.
Does it mean it is not supported?

Please update documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a6439e-a119-688b-bb8a-b6fd0b8a37fb
* Version Independent ID: 8250980c-0bd3-6d89-fb0e-24f8ea6eafd8
* Content: [Custom connector FAQ for Azure Logic Apps, Power Automate, and Power Apps](https://docs.microsoft.com/en-us/connectors/custom-connectors/faq)
* Content Source: [docs/custom-connectors/faq.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/faq.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by v-aangie** [comment] 2021-08-18 20:29
@marcindabrowski - 
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed** 2021-08-18 20:29 UTC
Labels: open-for-too-long

**Comment by RedsGT** [comment] 2021-09-20 04:36
The FAQ has now been updated to show this is not supported.

**Comment by elenoico** [comment] 2023-07-25 13:34
It is not supported by Microsoft. You can vote for it to be implemented here:
[https://ideas.powerautomate.com/d365community/idea/34f24f0e-75ba-4dc4-8979-be261ecd8a55](url)
