### ISSUE TITLE
Issue with the title

### ISSUE THREAD

**Issue by dannyh-vmw** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#236] opened 2020-11-09 19:03 UTC
Mangled page title

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 697bacb2-e3d7-3422-5ea2-73c17fc1f2c6
* Version Independent ID: 443505c2-0c7e-5a56-4cc2-74caf84529f9
* Content: [}exghts gen. Document & more - Connectors](https://docs.microsoft.com/en-us/connectors/docq/#feedback)
* Content Source: [docs/docq/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/docq/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by dougelliott** [comment] 2020-12-31 00:14
Hi @dannyh-vmw - Thanks for the feedback. This is the name of the connector and not a bug with the documentation, so everything is as intended. I will go ahead and close this as a result.

**Closed by dougelliott** 2020-12-31 00:14 UTC
Labels: invalid
