### ISSUE TITLE
Missing, incomplete or incorrect Documentation - does not correspond to Office 365 Outlook PowerApps connector implementation

### ISSUE THREAD

**Issue by BrazilianJoe** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#135] opened 2020-06-22 12:24 UTC
Hi,

The documentation does not match the way the contact-related functions. 
Create Contact V2
Update Contact V2

The parameter list is showing the same list as for Create/update V1. 
The correct would be to display a parameter list that matches the structure of the response of Get Contact V2. 

All parameters that are records or arrays of records are not correctly described. 
This is especially troublesome because the array of emailAddresses is not described at all (most basic piece of information for an email contact). 

Phones and addresses are also not described according to the implementation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca6193ac-2539-73fb-27a8-134722eac6ac
* Version Independent ID: c9a83b37-0105-cf97-d5b9-ad20a4420986
* Content: [Office 365 Outlook - Connectors](https://docs.microsoft.com/en-us/connectors/office365connector/)
* Content Source: [docs/Office365Connector/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Office365Connector/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment] 2021-08-19 20:19
@BrazilianJoe - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 20:19 UTC
Labels: doc-request, open-for-too-long
