### ISSUE TITLE
Extending GitHub Connecotrs with more actions

### ISSUE THREAD

**Issue by navin22** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#151] opened 2020-07-09 06:22 UTC
Hi Team,

We wanted to extend the existing GitHub connector with more actions like, creating a commit, PR or importing from the GitHub. Which Power platform users can use to build devops/ALM around Power Platform.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90cc63c5-330d-3be1-73c7-ef14c3531007
* Version Independent ID: 16bc26a2-2aee-7438-40b3-30732c7ed1f8
* Content: [GitHub - Connectors](https://docs.microsoft.com/en-us/connectors/github/)
* Content Source: [docs/GitHub/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/GitHub/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment] 2020-08-11 23:16
Thank you for your feedback. This is now under review and no further action is required at this time.

**Comment by bezhan-msft** [comment] 2020-08-11 23:18
Hi Navin - I see you are in the Microsoft organization - are you an internal employee?

**Comment by navin22** [comment] 2020-08-20 15:54
Yes. And I got connected to BAPI Connectors team internally. 

We can close this issue for now. 😊

**Comment by v-aangie** [comment] 2021-08-19 20:28
@navin22 - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 20:28 UTC
Labels: under-review, open-for-too-long
