### ISSUE TITLE
Expand on "Comment" description on "Forward an Email V2"

### ISSUE THREAD

**Issue by jhardwick-nxio** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#85] opened 2020-05-06 19:01 UTC
A description that is the same as the name isn't really a description is it? :)  Is this text that gets added when the email is forwarded or is it really just a random comment field?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc40a098-af8c-d8a9-4538-71d184efbe91
* Version Independent ID: 0ee8cf79-18e9-d923-607f-ef40cdd23e4d
* Content: [Office 365 Outlook - Connectors](https://docs.microsoft.com/en-us/connectors/office365/#feedback)
* Content Source: [docs/office365/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/office365/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment] 2021-08-19 18:09
@jhardwick-nxio - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed by v-aangie** 2021-08-19 18:09 UTC
Labels: open-for-too-long
