### ISSUE TITLE
Missing ARM template definition

### ISSUE THREAD

**Issue by brandonh-msft** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#48] opened 2020-04-07 23:30 UTC
Needs to call out what properties of the connection in an ARM Template must be set (e.g. how to set the SAS token in an ARM template)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6beb11cb-c11b-24c1-760d-8bc91716737a
* Version Independent ID: 1bd6a84f-d3c8-dd8a-1e4d-d5161ed7927a
* Content: [Azure Event Grid Publish - Connectors](https://docs.microsoft.com/en-us/connectors/azureeventgridpublish/#feedback)
* Content Source: [docs/azureeventgridpublish/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/azureeventgridpublish/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment] 2020-04-29 23:22
Thank you for your feedback. This is now under review and no further action is required at this time.

**Comment by abolsen** [comment] 2020-09-16 07:15
any news on this one? Impossible to deploy an Azure Event Grid Publish connector with a SAS token without knowing parameters. So we have to manually add the token to connect, after deployment of the ARM template.

**Comment by brandonh-msft** [comment] 2020-09-16 16:57
> any news on this one? Impossible to deploy an Azure Event Grid Publish connector with a SAS token without knowing parameters. So we have to manually add the token to connect, after deployment of the ARM template.

I've solved for event grid w/ some reverse engineering. You can see it [here](https://github.com/Azure-Samples/serverless-keyvault-secret-rotation-handling/blob/4c948d23690859dc2dce8db90e3a49d54d192e1c/terraform/main.tf#L290).

**Comment by abolsen** [comment] 2020-09-16 17:57
> > any news on this one? Impossible to deploy an Azure Event Grid Publish connector with a SAS token without knowing parameters. So we have to manually add the token to connect, after deployment of the ARM template.
> 
> @abolsen, I solved for event grid w/ some reverse engineering. You can see it [here](https://github.com/Azure-Samples/serverless-keyvault-secret-rotation-handling/blob/4c948d23690859dc2dce8db90e3a49d54d192e1c/terraform/main.tf#L290).

Thanks, but I'm looking into the Event Grid Publish API (azureeventgridpublish), and not the event grid connector (azureeventgrid).

So I have something like this, but would like to pass a SAS token in the parameterValue section (which is what I'm doing today manually in the portal once it's deployed):

`    {
      "type": "Microsoft.Web/connections",
      "apiVersion": "2016-06-01",
      "name": "[parameters('connections_azureeventgridpublish_name')]",
      "location": "westeurope",
      "properties": {
        "displayName": "eventgridpublish",
        "customParameterValues": {},
        "api": {
          "id": "[concat('subscriptions/', subscription().subscriptionId, '/providers/Microsoft.Web/locations/', resourceGroup().location, '/managedApis/azureeventgridpublish')]"
        },
        "parameterValues": {
          "endpoint": "[parameters('grid_publish_topic_endpoint')]"
        }
      }
    }`

**Comment by ssidnal** [comment] 2021-08-09 20:46
Any update on this? @abolsen  how did you able to resolve this?

**Comment by abolsen** [comment] 2021-08-10 06:53
This is still an issue. You could set and send the authorization directly in your events as a workaround.
But as far as I know, there's no way to set up the SAS in the connection resource, unfortunately. It isn't documented at least.

**Comment by ssidnal** [comment] 2021-08-10 13:09
@abolsen i was able to figure out that adding a key “api_key” at this he same level of “endpoint” key adds SAS to the connection. Also it wont be visible if you are trying to verify post ARM template publish but connection will be made successfully. Try this!!

**Comment by v-aangie** [comment] 2021-08-18 20:42
@brandonh-msft - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed** 2021-08-18 20:43 UTC
Labels: documentation, under-review, open-for-too-long

**Comment by brandonh-msft** [comment] 2021-08-18 20:51
@v-aangie I'm not sure what you mean. The linked document still doesn't have in it what parameters **in an ARM Template** need to be set to populate the SAS Key for an Event Grid connection. This should remain open until such documentation is provided and users don't have to reverse-engineer the canvas & REST calls to figure it out.

**Comment by v-aangie** [comment] 2021-08-18 22:03
@brandonh-msft - As part of maintenance, we’re closing all issues that have been open for over a year. The documentation has been updated to now show where to submit new issues here: https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

Issue #48 was open April 7, 2020 I suggest moving this issue to one of the forums in the doc. If this doesn’t work for you, I’ll need to pull in another team member. We’ll make sure your issue lands in a place where it can get appropriate attention.

**Comment by brandonh-msft** [comment] 2021-08-18 22:09
Thanks for that explanation @v-aangie . GH has an option to [Transfer an Issue to another Repository](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository). Could we do that for this one, by chance?

**Comment by brandonh-msft** [comment] 2021-08-18 22:17
[Done](https://powerusers.microsoft.com/t5/Connector-Development/Event-Grid-Connector-is-Missing-ARM-template-definition/m-p/1235616#M339)

**Comment by mamurshe** [comment] 2021-08-24 19:31
@v-aangie why would an internal documentation bug be forwarded to forum? Forum is for customer question.

**Comment by mamurshe** [comment] 2021-08-24 19:38
@v-aangie @brandonh-msft let's schedule a meeting on this. @brandonh-msft what's your microsoft alias or email address? Can't seem to find you info in github or directory.

**Comment by v-aangie** [comment] 2021-08-25 14:36
@mamurshe @brandonh-msft - As part of maintenance, we're closing issues that were created over a year. We tell users to either reopen (for doc bugs) or go to the forums page (to submit questions or ideas). I don't anticipate that closing issues will continue, as issues shouldn't take that long.

**Here's the response for issues open over a year:**
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Comment by SeshuKalakurthi** [comment] 2021-09-17 14:23
I got the SAS key for my Event Grid, I need the parameter name of the SAS key in ARM, whether we can give like 'api_key' or 'SAS key' below the endpoint parameter.
