### ISSUE TITLE
Info for people trying to understand how to use this

### ISSUE THREAD

**Issue by thomassandsor** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#24] opened 2020-03-12 19:29 UTC
https://saralagerquist.com/2019/12/15/cds-vs-cds-what-connector-should-i-use-in-power-automate/

The new connector for current environment is wierd with lookups.. No idea why

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78bf3518-bce4-ecc5-8bf6-1fb627b9105e
* Version Independent ID: d46568f2-e080-cbbe-2f7e-a655bce20b64
* Content: [Common Data Service (current environment) - Connectors](https://docs.microsoft.com/en-us/connectors/commondataserviceforapps/#feedback)
* Content Source: [docs/commondataserviceforapps/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/commondataserviceforapps/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment] 2020-03-21 22:38
Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback)

**Comment by bezhan-msft** [comment] 2020-03-21 22:38
Noted - we may be able to document this. Assigning for further investigation

**Comment by v-aangie** [comment] 2021-08-16 17:40
@thomassandsor - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by v-aangie** 2021-08-16 17:40 UTC
Labels: documentation, under-review, open-for-too-long
