### ISSUE TITLE
Update connector doc to specify the date-time format expected by the google API

### ISSUE THREAD

**Issue by lordneeko** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#128] opened 2020-06-10 19:10 UTC
[Enter feedback here]
Even through trial and error, I cannot figure out the required format for date-time by the connector. I keep getting an error that the date-time is not formatted correctly, but it doesn't give any info on what format is expected. The Google Calendar connector documentation doesn't specify either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 352d2e69-2be4-03c9-9fa8-f3b9795cab42
* Version Independent ID: 8889e801-9db2-aab1-ebf3-1340ae15f0f1
* Content: [Google Calendar - Connectors](https://docs.microsoft.com/en-us/connectors/googlecalendar/#create-an-event)
* Content Source: [docs/GoogleCalendar/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/GoogleCalendar/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment] 2021-08-19 19:28
@lordneeko - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 19:28 UTC
Labels: doc-request, open-for-too-long
