### ISSUE TITLE
Add Member to Group doesn't work for guests

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#131] opened 2020-06-17 16:45 UTC
https://docs.microsoft.com/en-us/connectors/office365groups/#add-member-to-group

This doc doesn't say there are any limitations on what types of users you can specify for a UPN with this action.  It doesn't work when specifying a guest's source UPN (barney.rubble@flintstone.com) or the UPN as it exists in the tenant hosting the guest account with the EXT (Barney.Rubble_bedrock.onmicrosoft.com#EXT#@bedrock.onmicrosoft.com)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66d136b3-75bc-fd53-2d17-15f0904a0b54
* Version Independent ID: 71609855-7cb2-9994-e8f3-13fe93d9aa54
* Content: [Office 365 Groups - Connectors](https://docs.microsoft.com/en-us/connectors/office365groups/#known-issues-and-limitations)
* Content Source: [docs/office365groups/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/office365groups/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment] 2021-08-19 19:35
@poortom1004 - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 19:36 UTC
Labels: doc-request, open-for-too-long
