### ISSUE TITLE
Service Bus SDK and version

### ISSUE THREAD

**Issue by SeanFeldman** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#133] opened 2020-06-18 20:27 UTC
It would be nice if the documentation would either provide the Azure Service Bus SDK and the version used by the connector or point to the implementation repository (if public).

I found https://github.com/logicappsio/AzureServiceBusTrigger and not sure if that's what LogicApps is currently using or not. The `master` branch indicates [`WindowsAzure.ServiceBus` version 3.2.2](https://github.com/logicappsio/AzureServiceBusTrigger/blob/8e9fdeafa119187075722f0cf37b6f39e007caa7/AzureServiceBusTrigger/AzureServiceBusTrigger.csproj#L100) is used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2658ff5e-3ad5-4c91-4442-3ab99b8b5bf0
* Version Independent ID: e1daa665-94cc-bdf8-ce4c-674d4ee564fc
* Content: [Service Bus - Connectors](https://docs.microsoft.com/en-us/connectors/servicebus/)
* Content Source: [docs/ServiceBus/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/ServiceBus/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment] 2021-08-19 20:12
@SeanFeldman - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 20:13 UTC
Labels: doc-request, open-for-too-long

**Comment by SeanFeldman** [comment] 2021-08-20 05:19
Only took 2 years... no wonder no relevant information could be found 😀
