### ISSUE TITLE
No documentation related to Manual Trigger Custom Connector

### ISSUE THREAD

**Issue by deepdiwakar9** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#117] opened 2020-05-31 07:46 UTC
On using Microsoft Power Platform, I got to know about Manual triggers in custom connector. Sharepoint & Onedrive (Buisness) has manual trigger "when a file is selected" and that can be used to define a Instant Type Workflow.
Flows can be automated (which uses webhook type trigger) or instant (which uses manual trigger e.g. Button, Sharepoint when a file selected etc.)
Would love to know about how to define manual flow in your custom connector?

P.S. -  Manual trigger can be easily called from your own website using flow APIs, sharepoint does the same it checks for workflows current user has and then do a POST call to that manual trigger.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0df6a505-f725-a402-da3d-4e400e0f6fc1
* Version Independent ID: fad34bde-59a4-4330-c389-15ce64ac08b8
* Content: [Use a webhook as a trigger for Azure Logic Apps and Power Automate](https://docs.microsoft.com/en-us/connectors/custom-connectors/create-webhook-trigger)
* Content Source: [docs/custom-connectors/create-webhook-trigger.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/create-webhook-trigger.md)
* Service: **flow**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by v-aangie** [comment] 2021-08-19 19:01
@deepdiwakar9 - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed by v-aangie** 2021-08-19 19:01 UTC
Labels: documentation, doc-request, open-for-too-long
