### ISSUE TITLE
How to use this connector

### ISSUE THREAD

**Issue by mgoto-git** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#132] opened 2020-06-18 00:58 UTC
[フィードバックをこちらに入力してください]
I tried "Sync messages to Planner" action. 
This action can't be configured any input parameters.
So I  just executed it from manual trigger, but it returned below error.
"{
  "error": {
    "code": 403,
    "source": "-001.azure-apim.net",
    "clientRequestId": "*************",
    "message": "The response is not in a JSON format.",
    "innerError": "Cannot read server response."
  }
}
"
How to use this connector?
Any pre-requirements?

 

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 5ca61b80-8455-08a9-2882-89769ce9a167
* Version Independent ID: e151d712-44ff-0462-b9eb-ffcd9c9714c1
* Content: [Microsoft 365 message center - Connectors](https://docs.microsoft.com/ja-jp/connectors/m365messagecenter/)
* Content Source: [docs/m365messagecenter/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/m365messagecenter/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bhaub78** [comment] 2020-06-22 18:56
What permissions are required on Microsoft 365 to allow the connector to retrieve data?  It's not listed in the documentation and the error message doesn't provide any detail.

**Comment by mgoto-git** [comment] 2020-07-29 02:52
OK ,I realized.
Today, "Sync to Planner" button was appeared on AdminPortal's Message Center.
It can make sync configuration,(which Plan is to use to be synced  etc.) and then , configure the flow with use this connector.
This connector is not available on itself but is available with the "Synchronize to Planner" button in message center.
("Sync to Planner" button seems to be delayed by tenants.)

**Comment by v-aangie** [comment] 2021-08-19 20:16
@mgoto-git - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 20:17 UTC
Labels: doc-request, open-for-too-long
