### ISSUE TITLE
Properties missing from "Get user profile (V2)"

### ISSUE THREAD

**Issue by MrAzureAD** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#23] opened 2020-03-12 13:54 UTC
"Get user profile (V2)" references the Graph user properties.
But not all properties are available, e.g. onPremisesExtensionAttributes is not available.

I would rather like the missing attributes added than the documentation corrected.
But currently it does not match.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8635712-d5a2-e58a-301f-cf849f2cf2e4
* Version Independent ID: 4cfdd73e-f074-0446-2aee-2dd013a8b30f
* Content: [Office 365 Users - Connectors](https://docs.microsoft.com/en-us/connectors/office365users/#feedback)
* Content Source: [docs/office365users/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/office365users/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment] 2020-03-12 23:43
Hello - thank you for your feedback.

To confirm, are you attempting to match the connector documentation with the API documentation?

**Comment by MrAzureAD** [comment] 2020-03-16 13:16
Currently, the documentation refers to the Graph documentation for available user attributes.
However, not all attributes are currently available.
Either A) make all attributes available OR B) correct the documentation and list the really available attributes.

I would really like A)

**Comment by mathieuchateau** [comment] 2020-03-19 11:32
I agree, I have same issue

**Comment by bezhan-msft** [comment] 2020-03-19 23:12
I understand the issue to be that - there is functionality missing (i.e. there are attributes missing) from the connector action and that is not well documented.

If you would like attributes added, please file a query to the [product forums].(https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback)

We will need to investigate on our side which limitations there are on these attributes and how to best document them.

**Comment by robertcaretta** [comment] 2020-05-06 21:56
Why do we have to request that attributes be added? Shouldn't the Office 365 Users connector match what is available in the Graph API?  I mean street address, for one is missing.

**Comment by MrAzureAD** [comment] 2020-05-07 05:24
The choice of attributes is arbitrary and the choice is not documented. Requesting individual attributes sounds wrong to me - and I am quite sure you will not want to cope with a high number of individual requests. 
If you want the functionality to be used, the full set of attributes should be available - that is the strength of Graph. If every Microsoft app supports only a half baked set of Graph, the traction will be lost.

**Comment by cbyappert** [comment] 2020-05-07 16:49
Running into this myself ... around employeeID Really need this for some cross application integration. May have to do this via an HTTP GET against the graph api. .. which will be a pain.

**Comment by drhallahan** [comment] 2020-05-09 22:59
I thought forms and flow would be a great fit for my use case as we have E5 plan but this isn't really usable. employeeID and the onprem attributes are the main missing ones for me. But really, all properties should be available, especially considering you provide a selection input already.

**Comment by cbyappert** [comment] 2020-05-09 23:05
so here is how we are getting around this .. we have regular batch job that takes our core, HR and extended on-prem AD attributes and writes them to a database (our data warehouse actually)... then we go get the data from there. Frankly, you could use any location for data: Excel, SharepointOnline.

This has the added advantage that I can now use that information in the DB to join with other data set for

**Comment by robertcaretta** [comment] 2020-05-09 23:40
Does the Graph API expose any of that?

**Comment by cbyappert** [comment] 2020-05-09 23:47
well interestingly .. the graph API is a bit broken as well in that you can't seem to get employeeID. Well, I couldn't at least

the point is it's broken and it needs to be fixed .. You can work around it .. but it makes things messy and it shouldn't have to be. What's funny is that Micorosft actually has to work harder to not do it than to just let it thru.

**Comment by robertcaretta** [comment] 2020-05-10 00:01
employeeID is listed here in the Graph API Beta.  Look under the details
for User object.
https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta

**Comment by MrAzureAD** [comment] 2020-05-10 08:58
@bezhan-msft This issue is open for almost 2 months and documentation still points to Graph and does not mention the restrictions on fields. This is wrong and confusing.

I would recommend two steps:
1) Immediately correct the docs that it reflects the existing implementation (e.g. Currently only the following attributes are available: <list of fields>).
2) Work on getting all attributes supported  

If it helps to open a premier support case, DCR or escalate otherwise, let me know.

**Comment by mathieuchateau** [comment] 2020-05-10 09:44
@MrAzureAD : I think I can I get a premier support case too if it helps

**Comment by MrAzureAD** [comment] 2020-05-10 09:54
In my experience, premier support will just close the case as "works-as-designed". A DCR might be better suited, but in the past it took ages to reach the right group and typically it was then declined ...
I would let @bezhan-msft decide on how to proceed.

**Comment by drhallahan** [comment] 2020-05-10 20:59
I suspect that as it stands this is just a doc bug rather than a feature request for the connector itself. Will look at the support case route too here as it would be useful.
________________________________

**Comment by v-aangie** [comment] 2021-08-16 17:34
@MrAzureAD - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by v-aangie** 2021-08-16 17:34 UTC
Labels: product-support, product-feedback, open-for-too-long

**Comment by robertcaretta** [comment] 2021-08-16 19:40
Did a users street address ever get added?

**Comment by rnwoodhcl** [comment] 2022-06-08 15:00
@v-aangie Please see previous comment and consider re-opening this issue.

**Comment by eversonl** [comment] 2022-07-07 16:22
Hi, this is accessible via flow 
`{
    "host": {
        "connectionReferenceName": "shared_office365users",
        "operationId": "UserProfile_V2"
    },
    "parameters": {
        "id": "joe@loungers.co",
        "$select": "onPremisesExtensionAttributes,jobTitle,mail"
    }
}`

but there seems to be no way of getting to this via power canvas 
what would the equivalent syntax be? 'Office365Users.UserProfileV2({ThisItem.Id).$select:onPremisesExtensionAttributes,jobTitle,mail'

**Comment by Santiagosala2** [comment] 2022-12-15 23:49
@eversonl  @rnwoodhcl I found a way to achieve this for Power Apps canvas but it requires unpacking the app using the Power Platform tools on vs code , modifying the Office365Users.xml file and packing it back .

Disclaimer "Warning: canvas pack is in preview, and functionality is not guaranteed. Use extreme caution if using in a production environment. For more information see https://aka.ms/paccanvas"

1. Unpack the app with the Power Platform tools (https://www.youtube.com/watch?v=vsd2WuNx_Cg&t=715s)
2. Find the Wadl folder (pkgs/Wadl) and then open the Office365Users.xml file
3. Inside <grammars> <jsonTypes> you want to look for "GraphUser_V1" which is the response's definition for the UserProfileV2

![image](https://user-images.githubusercontent.com/57156913/207987133-e101a177-1fe2-4ebb-926f-17674f9fe8ec.png)

4. Paste the following obj - below the "GraphUser_V1_...._def"s
```
<object name="onPremisesExtensionAttributes_def">
        <property name="extensionAttribute1" type="string" />
        <property name="extensionAttribute2" type="string" />
     ........
</object>
```
![image](https://user-images.githubusercontent.com/57156913/207987537-df6f7f3a-8a3a-4732-8e69-424fab8d89b6.png)

5. Then attach the above def for onPremisesExtensionAttributes into the "GraphUser_V1" obj def

 `<property name="onPremisesExtensionAttributes" typeRef="onPremisesExtensionAttributes_def" />`

![image](https://user-images.githubusercontent.com/57156913/207988040-99978cb8-8633-4011-b957-5f9733a15df3.png)


7. Pack the app using the Power Platform tools (please refer to the video) and upload it

8. Now on the canvas editor you will see that you got intellisense for onPremisesExtensionAttributes and that the response from UserProfileV2 maps the values for onPremisesExtensionAttributes 
![image](https://user-images.githubusercontent.com/57156913/207988774-2d1f54b4-44e8-4627-9ced-b16bf9b3d5b7.png)

**Comment by scottvpeters** [comment] 2023-10-03 19:24
Hello are there any updates on this from MS?
