### ISSUE TITLE
Example needed to explain how to use SetHostUrl.

### ISSUE THREAD

**Issue by Davesmall28** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#141] opened 2020-06-26 22:03 UTC
Can we get an example of how to set the host url so that we can use a custom connector in dev, test and production?

Do we need to use the Power Automate CLI to create the custom connector?

Regards,

David

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3817394-e2f3-da6b-797c-552ae6f3e71f
* Version Independent ID: b0e24b14-8f7c-57e4-e7e7-4e0447dcf354
* Content: [Set Host URL](https://docs.microsoft.com/en-gb/connectors/custom-connectors/policy-templates/dynamichosturl/dynamichosturl)
* Content Source: [docs/custom-connectors/policy-templates/dynamichosturl/dynamichosturl.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/policy-templates/dynamichosturl/dynamichosturl.md)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment] 2021-08-19 20:24
@Davesmall28 - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed by v-aangie** 2021-08-19 20:24 UTC
Labels: documentation, doc-request, open-for-too-long
