### ISSUE TITLE
"Connector" cannot be used as "Idea Labels"

### ISSUE THREAD

**Issue by MrAzureAD** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#93] opened 2020-05-10 09:30 UTC
Power Apps Ideas has only a limited set of "Idea Labels". The mentioned label "Connector" is unfortunately not available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a6df7b0-04ac-5f64-d641-db13bfd34a00
* Version Independent ID: afccffbb-7b4c-d351-3a0f-ada16c5ce282
* Content: [Instructions on providing feedback for connectors](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback#feedback)
* Content Source: [docs/custom-connectors/provide-feedback.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/provide-feedback.md)
* Service: **connectors**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by v-aangie** [comment] 2021-08-19 18:35
@MrAzureAD - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 18:35 UTC
Labels: documentation, doc-request, open-for-too-long
