### ISSUE TITLE
Streaming API?

### ISSUE THREAD

**Issue by kvansaders** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#122] opened 2020-06-05 15:31 UTC
I don't see any documentation on connecting to the Salesforce Streaming API.  Is that supported by this connector or any other connector in Azure?

**Comment by v-aangie** [comment] 2021-08-19 19:10
@kvansaders - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 19:10 UTC
Labels: documentation, open-for-too-long
