### ISSUE TITLE
Add specific table column requirements for the two Azure SQL Server triggers

### ISSUE THREAD

**Issue by cveld** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#115] opened 2020-05-29 07:08 UTC
Please add the specific table column requirements for the two Azure SQL Server triggers as stated on this blog:
https://flow.microsoft.com/en-us/blog/introducing-triggers-in-the-sql-connector/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58c0b60a-fdc5-6ce7-e73f-c5071c0f9356
* Version Independent ID: 5865c7d1-abc2-4a70-56dd-4ebef0b411c4
* Content: [SQL Server - Connectors](https://docs.microsoft.com/en-us/connectors/sql/#when-an-item-is-modified-(v2))
* Content Source: [docs/Sql/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Sql/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by sven5** [comment] 2020-07-23 08:06
Yes the documentation lacks the limitations of the blog entry.

Please add the following to the docs:
```
Limitations
The triggers do have the following limitations:

It does not work for on-premises SQL Server
Table must have an IDENTITY column for the new row trigger
Table must have a ROWVERSION (a.k.a. TIMESTAMP) column for the modified row trigger
```

**Comment by v-aangie** [comment] 2021-08-19 18:59
@cveld - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed by v-aangie** 2021-08-19 18:59 UTC
Labels: doc-request, open-for-too-long
