### ISSUE TITLE
Get Contacts V2: default value is incorrect

### ISSUE THREAD

**Issue by BrazilianJoe** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#138] opened 2020-06-23 17:33 UTC
De description for Get Contacts V2 is incorrect. 
It says that the default value for the $top parameter is 'all', to fetch all contacts. 
This does not match the function behavior. 
If you don't provide the $top parameter, only the first 10 Contacts are returned. 
The default value for $top is 10. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca6193ac-2539-73fb-27a8-134722eac6ac
* Version Independent ID: c9a83b37-0105-cf97-d5b9-ad20a4420986
* Content: [Office 365 Outlook - Connectors](https://docs.microsoft.com/en-us/connectors/office365connector/#get-contact-(v2))
* Content Source: [docs/Office365Connector/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Office365Connector/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment] 2021-08-19 20:21
@BrazilianJoe - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 20:21 UTC
Labels: doc-request, open-for-too-long
