### ISSUE TITLE
Samples needed for Insert row action

### ISSUE THREAD

**Issue by jurijsk** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#130] opened 2020-06-17 15:51 UTC
Samples needed. I'm trying to use "Insert row" action, but can not get it to work. At least add links to Google Sheets API docs or expose what exactly you send to Google API. Otherwise, what is the point of creating a bunch of connector and no documentation.

How is knowing that 

Name | Key | Required | Type | Description
-- | -- | -- | -- | -- 
Row | item | True | dynamic | Row to insert into the specified sheet.

can be helpful to anyone?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bdbb512-183a-7dc1-5d2e-752a0add719e
* Version Independent ID: 1688ea0e-6848-e51a-1e17-552a9c20fbe5
* Content: [Google Sheets - Connectors](https://docs.microsoft.com/en-us/connectors/googlesheet/#insert-row)
* Content Source: [docs/GoogleSheet/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/GoogleSheet/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment] 2021-08-19 19:34
@jurijsk - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed by v-aangie** 2021-08-19 19:34 UTC
Labels: doc-request, open-for-too-long
