### ISSUE TITLE
How to insert Dynamic Link into Body?

### ISSUE THREAD

**Issue by HandyAndyOnGitHub** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#155] opened 2020-07-13 00:22 UTC
Would you please add an example to demonstrate how to insert a Dynamic Link into the Body of "Send an email notification (V3)"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59e25400-ea5a-a77a-65e3-f5f7bd7b17a9
* Version Independent ID: 15fb9fda-6420-5f6e-1a4e-74997a5d7dfb
* Content: [Mail - Connectors](https://docs.microsoft.com/en-us/connectors/sendmail/)
* Content Source: [docs/SendMail/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/SendMail/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment] 2021-08-19 21:10
@HandyAndyOnGitHub - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 21:10 UTC
Labels: doc-request, open-for-too-long
