### ISSUE TITLE
Known Issues and Limitations Section Not Complete

### ISSUE THREAD

**Issue by codeBoarder** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#3] opened 2020-02-24 21:44 UTC
In the "Known Issues and Limitations Section", it should be noted that at this time the Azure Storage Connector does not support operations where the Logic App is running under a managed identity and connecting to a storage account secured behind a firewall in the same region. 

An example would be a storage account where the "allow trusted Microsoft services to access this storage account" option is checked under exceptions in the "Firewalls and Virtual Networks" configuration section. When trying to connect to a storage account in this situation in the same region, an HTTP action is needed to make sure the correct authentication against the storage account RBAC roles occurs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4a1ef15-eee8-e31f-e05d-34ae84216545
* Version Independent ID: 01cf0d74-3e50-c6c9-fe0d-7d639886318c
* Content: [Azure Blob Storage - Connectors](https://docs.microsoft.com/en-us/connectors/azureblob/#known-issues-and-limitations)
* Content Source: [docs/azureblob/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/azureblob/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment] 2020-03-07 01:10
Thank you for your feedback. This is now under review and no further action is required at this time.

**Comment by v-aangie** [comment] 2021-08-16 17:21
@codeBoarder - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by v-aangie** 2021-08-16 17:21 UTC
Labels: wontfix, under-review
