### ISSUE TITLE
Can I use Custom Connector with the Business Only connectors from DLP?

### ISSUE THREAD

**Issue by dhawal16** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#96] opened 2020-05-13 14:32 UTC
Hello,
Can you please also confirm here if Custom Connector can be use with the Business Only connectors from DLP? I am not able to find any clarity on this.

Thanks,
Dhawal Mehta

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a6439e-a119-688b-bb8a-b6fd0b8a37fb
* Version Independent ID: 8250980c-0bd3-6d89-fb0e-24f8ea6eafd8
* Content: [Custom connector FAQ for Azure Logic Apps, Power Automate, and Power Apps](https://docs.microsoft.com/en-us/connectors/custom-connectors/faq)
* Content Source: [docs/custom-connectors/faq.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/faq.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by v-aangie** [comment] 2021-08-19 18:36
@dhawal16 - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed by v-aangie** 2021-08-19 18:36 UTC
Labels: documentation, doc-request, open-for-too-long
