### ISSUE TITLE
Crashes When I Try To Enter This OAuth Info

### ISSUE THREAD

**Issue by mikeswain** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#68] opened 2020-04-25 03:18 UTC
Yep, tried to do this  a couple of times but just fails with

Encountered internal server error. Diagnostic information: timestamp '20200425T030655Z', subscription id '6f4c2473-f8cb-4b18-8796-f4cf662c01fe', tracking id '62c1c6da-c4d0-47ad-9e75-ecd640fabf82', request correlation id '62c1c6da-c4d0-47ad-9e75-ecd640fabf82'.

Nothing in activity log, just doesn't save connection info
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbe19853-b922-4f26-95e3-64e577a9ce62
* Version Independent ID: c108c332-4573-55d1-7c1d-e7a45ae58b39
* Content: [Specifying connection parameters](https://docs.microsoft.com/en-us/connectors/custom-connectors/connection-parameters)
* Content Source: [docs/custom-connectors/connection-parameters.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/connection-parameters.md)
* Service: **connectors**
* GitHub Login: @revanth1996
* Microsoft Alias: **jeconnoc**

**Comment by bezhan-msft** [comment] 2020-04-29 23:01
Thank you for your feedback. This is now under review and no further action is required at this time.

@DougKlopfenstein can you take a look please?

**Comment by bezhan-msft** [comment] 2020-05-20 22:18
Hello - we have tried recently and confirmed that there is no error in the documentation and that the workflow does not err out. 

For further support on this please reach out to our product support through the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback).

**Comment by v-aangie** [comment] 2021-08-19 17:35
@mikeswain - 
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 17:36 UTC
Labels: under-review, open-for-too-long
