### ISSUE TITLE
Known Issues and Limitation

### ISSUE THREAD

**Issue by dwolfe2020** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#15] opened 2020-03-03 22:43 UTC
What are the specific limitations when a JIRA Server is behind a firewall?  Do ports need to be opened etc.?  Please add more detail to help diagnose - Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76d2c23e-c66c-3e66-f61d-681c4327e461
* Version Independent ID: 0c4a4d9e-d055-d56e-6b48-c70cb753aa60
* Content: [JIRA - Connectors](https://docs.microsoft.com/en-us/connectors/jira/#feedback)
* Content Source: [docs/JIRA/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/JIRA/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment] 2020-03-21 22:30
Thank you for your feedback. This is now under review and no further action is required at this time.

**Comment by GPHNKN** [comment] 2020-05-14 10:36
hello is there any update on this?

**Comment by v-aangie** [comment] 2021-08-16 17:26
@dwolfe2020 - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by v-aangie** 2021-08-16 17:26 UTC
Labels: wontfix, under-review
