### ISSUE TITLE
Need to specify units

### ISSUE THREAD

**Issue by tylerrencher** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#30] opened 2020-03-20 18:08 UTC
Special throttling limits section does not have units for the renewal period. Is it seconds, minutes, hours?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58c0b60a-fdc5-6ce7-e73f-c5071c0f9356
* Version Independent ID: 5865c7d1-abc2-4a70-56dd-4ebef0b411c4
* Content: [SQL Server - Connectors](https://docs.microsoft.com/en-us/connectors/sql/#feedback)
* Content Source: [docs/Sql/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Sql/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment] 2020-03-21 22:50
Thank you for your feedback. This is now under review and no further action is required at this time.

**Comment by cfu288** [comment] 2020-03-22 04:43
I’ve recently hit the throttle limits in a PowerApp, looks like it’s 300 api calls per 30 seconds. So I’m assuming the units for the rest of the refresh periods is also in seconds.

**Comment by v-aangie** [comment] 2021-08-16 17:44
@tylerrencher - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by v-aangie** 2021-08-16 17:44 UTC
Labels: documentation, under-review, open-for-too-long
