### ISSUE TITLE
HTTP missing from list of connectors 

### ISSUE THREAD

**Issue by JeneferM-MSFT** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#101] opened 2020-05-15 13:45 UTC
Looks like it didnt get added here when it was added? https://flow.microsoft.com/en-us/blog/introducing-http-and-custom-connector-support-for-data-loss-prevention-policies/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05311999-5cc3-eb54-779a-5340392b6437
* Version Independent ID: f6958b1c-6fc9-fd34-1535-eef6e36ef793
* Content: [Connectors Overview](https://docs.microsoft.com/en-us/connectors/connectors#feedback)
* Content Source: [docs/connectors.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/connectors.md)
* Service: **connectors**
* GitHub Login: @asavaritayal
* Microsoft Alias: **kvivek**

**Comment by v-aangie** [comment] 2021-08-19 18:50
@JeneferM-MSFT - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed by v-aangie** 2021-08-19 18:50 UTC
Labels: open-for-too-long
