### ISSUE TITLE
Clarify supported Jira version

### ISSUE THREAD

**Issue by koivumi2** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#46] opened 2020-04-07 07:07 UTC
As there are two versions of Jira (Jira Cloud and Jira Server) it would be important to clarify what versions and scenarios of Jira usage are actually supported by this connector.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76d2c23e-c66c-3e66-f61d-681c4327e461
* Version Independent ID: 0c4a4d9e-d055-d56e-6b48-c70cb753aa60
* Content: [JIRA - Connectors](https://docs.microsoft.com/en-us/connectors/jira/#feedback)
* Content Source: [docs/JIRA/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/JIRA/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment] 2020-04-29 23:43
Thank you for your feedback. This is now under review and no further action is required at this time.

**Comment by v-aangie** [comment] 2021-08-18 20:34
@koivumi2 - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by v-aangie** 2021-08-18 20:34 UTC
Labels: under-review, open-for-too-long
