### ISSUE TITLE
Need to update article with Frequency of trigger polls	

### ISSUE THREAD

**Issue by DavidPaf** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#32] opened 2020-03-23 03:49 UTC
Hi docs team,

Kindly review and update article with Frequency of trigger polls. I suppose this limit is omitted and now form responses appear in Microsoft Flow nearly instantaneously (under a minute)

Current Throttling Limit in public document is:
Frequency of trigger polls | 1 | 86400 seconds

![image](https://user-images.githubusercontent.com/61499598/77280265-6fb35600-6cf6-11ea-9e58-d8c2dbf4dea1.png)

Reference:
https://powerusers.microsoft.com/t5/Power-Automate-Ideas/Poll-Microsoft-Forms-for-new-data-more-often/idi-p/54908
https://flow.microsoft.com/en-us/blog/building-scratch-forms-responses/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a5a57d-aa82-9c07-5502-bd3be89773dc
* Version Independent ID: 5bdbf2ae-5c31-7a59-56f0-09d568602012
* Content: [Microsoft Forms - Connectors](https://docs.microsoft.com/en-us/connectors/microsoftforms/#feedback)
* Content Source: [docs/MicrosoftForms/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/MicrosoftForms/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment] 2020-04-29 23:26
Thank you for your feedback. This is now under review and no further action is required at this time.

@dougelliott I believe we reproduced this as well - please reach out to the product team on this.

**Comment by v-aangie** [comment] 2021-08-16 17:51
@DavidPaf - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by v-aangie** 2021-08-16 17:51 UTC
Labels: bug, under-review, open-for-too-long
