### ISSUE TITLE
Expression not working for Polling Triggers

### ISSUE THREAD

**Issue by nk-gears** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#8] opened 2020-02-26 10:54 UTC
The document doesn't provide much details on the expressions the polling triggers supports.

The triggerBody().data[0] works well. But in our scneario, the API doesn;t provides any sorting option so we need a way to create a expression to sort the results and pick the value accordingly.

something like  triggerBody().data[data.length-1] 

Could you please update the document with the exact expression to use for this scenario ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49d0e0df-c314-933d-43a9-c735081ddd5a
* Version Independent ID: a4aaf076-c72b-6585-b91c-ad98d5cd045d
* Content: [Use a polling trigger for Azure Logic Apps and Microsoft Power Automate](https://docs.microsoft.com/en-us/connectors/custom-connectors/create-polling-trigger)
* Content Source: [docs/custom-connectors/create-polling-trigger.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/create-polling-trigger.md)
* Service: **connectors**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **v-douklo**

**Comment by bezhan-msft** [comment] 2020-03-07 01:47
Thank you for your feedback. This is now under review and no further action is required at this time.

**Comment by nk-gears** [comment] 2020-04-29 03:49
Any updates on this ?

**Comment by v-aangie** [comment] 2021-08-16 17:23
@nk-gears - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by v-aangie** 2021-08-16 17:23 UTC
Labels: wontfix, under-review
