### ISSUE TITLE
Open API Definition file missing from tutorial

### ISSUE THREAD

**Issue by JustSlone** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#169] opened 2020-07-30 02:39 UTC
On this step: https://docs.microsoft.com/en-us/connectors/custom-connectors/create-webhook-trigger#import-the-openapi-definition

The tutorial says to upload the Open API definition we downloaded, but there is no file available to download. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0df6a505-f725-a402-da3d-4e400e0f6fc1
* Version Independent ID: fad34bde-59a4-4330-c389-15ce64ac08b8
* Content: [Use a webhook as a trigger for Azure Logic Apps and Power Automate](https://docs.microsoft.com/en-us/connectors/custom-connectors/create-webhook-trigger#import-the-openapi-definition)
* Content Source: [docs/custom-connectors/create-webhook-trigger.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/create-webhook-trigger.md)
* Service: **flow**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by v-aangie** [comment] 2021-08-20 15:13
@JustSlone - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed by v-aangie** 2021-08-20 15:13 UTC
Labels: documentation, open-for-too-long
