### ISSUE TITLE
Mention CORS regarding the Test wizard

### ISSUE THREAD

**Issue by Morgma** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#83] opened 2020-05-05 21:05 UTC
When defining a Custom Connector from scratch, under the "Defintion" tab on the Swagger Editor, it is possible to execute an API call and view the response and this may also be done on the "Test" tab. In either case, a sample curl command is displayed as if to indicate how the call is being made. However, there is never any mention of the fact that these calls will be executed from client-side Js, so for the test to work, the target API would need an allow exception for https://flow.microsoft.com and respond to pre-flight HTTP requests. 

I've made a suggestion that the Custom Connector dialogue support executing the API validation server-side, but until then, it would be useful for the docs to point out that an HTTP service may fail validation checks, but still work fine when executed server-side from a Flow:
https://powerusers.microsoft.com/t5/Power-Apps-Ideas/Custom-Connector-Test-Bench-CORS/idi-p/550075

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f873de3b-82f2-8cbc-0de3-6dbdc968b9fa
* Version Independent ID: ca3ccf84-5de8-ef66-9bda-b804404b5085
* Content: [Custom connectors overview](https://docs.microsoft.com/en-us/connectors/custom-connectors/#feedback)
* Content Source: [docs/custom-connectors/index.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/index.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by v-aangie** [comment] 2021-08-19 18:03
@Morgma - 
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 18:03 UTC
Labels: open-for-too-long
