### ISSUE TITLE
Values for parameter Roles in "Grant access to an item or a folder" action

### ISSUE THREAD

**Issue by Markus-Hanisch** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#168] opened 2020-07-28 13:10 UTC
Hi,
I would like to know what values the parameter `Roles` of the SharePoint Flow Action [Grant access to an item or a folder](https://docs.microsoft.com/en-us/connectors/sharepointonline/#grant-access-to-an-item-or-a-folder) accepts.
By default, the dropdown menu provides "can edit" and "can view".
Is it possible to enter a custom value to grant for example **Full Control** permissions or alike?
Where are the role values documented?

> Name | Key | Required | Type | Description
> -- | -- | -- | -- | --
> ... | ... | ... | ...| ...
> Roles | roleValue | True | string | Specify a role that is to be granted to the recipients

I also came across HTTP requests including a `roledefid` [ASSIGN UNIQUE PERMISSIONS TO A DOCUMENT WITH THE NEW SEND AN HTTP REQUEST TO SHAREPOINT ACTION (HOW TO USE THE SHAREPOINT REST API IN FLOW)](https://sergeluca.wordpress.com/2018/05/03/assign-unique-permissions-to-a-document-with-the-new-send-an-http-request-to-sharepoint-action-how-to-use-the-sharepoint-rest-api-in-flow/) by MVP Serge Luca, e.g.:
`_api/lists/getByTitle('_<listtitle>_')/items(_<itemID>_)/roleassignments/addroleassignment(principalid=_<principalid>_} ,roledefid=1073741826) `

(roledefid=1073741826) : means “read only”

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69a01872-3062-4100-f807-7d43e8111e9f
* Version Independent ID: 48560378-76ed-cb42-e816-894179e1f16d
* Content: [SharePoint - Connectors](https://docs.microsoft.com/en-us/connectors/sharepointonline/#grant-access-to-an-item-or-a-folder)
* Content Source: [docs/sharepointonline/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/sharepointonline/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment] 2021-08-20 15:11
@Markus-Hanisch - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-20 15:11 UTC
Labels: doc-request, open-for-too-long
