### ISSUE TITLE
ARM Template Connector Defintion

### ISSUE THREAD

**Issue by cwarne** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#158] opened 2020-07-15 22:19 UTC
Would it be possible to add ARM template connector documentation here as well? It is difficult to find the correct ARM template deployment information for all these connectors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1114b8b-0c42-b092-70dc-7a2b7c200376
* Version Independent ID: f0d4c89b-10fb-04f3-7aa9-042d27d59416
* Content: [SFTP - SSH - Connectors](https://docs.microsoft.com/en-us/connectors/sftpwithssh/)
* Content Source: [docs/sftpwithssh/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/sftpwithssh/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment] 2021-08-19 22:02
@cwarne - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed by v-aangie** 2021-08-19 22:02 UTC
Labels: doc-request, open-for-too-long
