### ISSUE TITLE
Office365 connector - add authn/authz information

### ISSUE THREAD

**Issue by lokijota** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#172] opened 2020-08-06 08:20 UTC
The page describes how the connector's API works, but not how the authentication process is done behind the scenes, specifically in terms of token issuance, token storage and lifetimes. All there is is a note in this other page https://docs.microsoft.com/en-us/azure/connectors/connectors-create-api-office365-outlook saying: 
*Your connection doesn't expire until revoked, even if you change your sign-in credentials. For more information, see Configurable token lifetimes in Azure Active Directory.* which is totally generic.

Is OpenId being used? OAuth2? Access tokens vs ID tokens? where can the validity of the token be changed or forced expired? what rights are being given to the LogicApps over the target O365 account? Even a brief explanation would be useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc40a098-af8c-d8a9-4538-71d184efbe91
* Version Independent ID: 0ee8cf79-18e9-d923-607f-ef40cdd23e4d
* Content: [Microsoft 365 Outlook - Connectors](https://docs.microsoft.com/en-us/connectors/office365/)
* Content Source: [docs/office365/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/office365/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by cveld** [comment] 2021-01-07 11:20
Also see Jeff Hollan's script to automate the consent which contains some clues:
https://github.com/logicappsio/LogicAppConnectionAuth/blob/master/LogicAppConnectionAuth.ps1

**Comment by v-aangie** [comment] 2021-08-20 15:27
@lokijota - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-20 15:27 UTC
Labels: doc-request, open-for-too-long

**Comment by cveld** [comment] 2021-08-21 08:33
Connectors such as these use AAD oauth user delegated consent. The connector's app registration is leveraged for this. The connection's security context is that of the user account you have used to consent with. The connection gets a refresh token which is valid for a period of 1 year. As long as you are using the connection frequently the connection will eventually pull a fresh refresh token from AAD.

As user delegated consent is applied, the authorization process cannot be automated fully unattended.

Maybe in future full automation will get provided? That will certainly help our use cases.
