### ISSUE TITLE
Request for auth information on connections

### ISSUE THREAD

**Issue by breakpoint7** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#165] opened 2020-07-27 13:34 UTC
It would be helpful to include authentication details on each connector (in the doc details) so we could tell which authentication pattern a connector uses. 
For instance: https://docs.microsoft.com/en-us/connectors/approvals/
Which auth pattern does it use?  https://docs.microsoft.com/en-us/power-platform/admin/wp-connectors

**Comment by v-aangie** [comment] 2021-08-19 22:13
@breakpoint7 - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed by v-aangie** 2021-08-19 22:13 UTC
Labels: doc-request, open-for-too-long
