### ISSUE TITLE
Formatted Values are not coming in the result

### ISSUE THREAD

**Issue by pavansarma93** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#65] opened 2020-04-24 12:33 UTC
Formatted values (Labels)  for optionsets in format : _fieldname_label is not present in the Output (for get/List record actions)(working on trigger) . (This is working in CDS connector) expected O/P below
{
  "statecode": 0,
  "_statecode_label": "Active"
}
Also the Formatted values for lookups are also very much needed in business scenarios to reduce unnecessary calls for just Name. expected O/P
{
   "_primarycontactid_value" : "2f0c8240-4b03-ea11-a811-000d3a6aafe4",
  "_primarycontactid_type" : "contact",
   "_primarycontact_label" : "John Doe"
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78bf3518-bce4-ecc5-8bf6-1fb627b9105e
* Version Independent ID: d46568f2-e080-cbbe-2f7e-a655bce20b64
* Content: [Common Data Service (current environment) - Connectors](https://docs.microsoft.com/en-us/connectors/commondataserviceforapps/)
* Content Source: [docs/commondataserviceforapps/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/commondataserviceforapps/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment] 2020-04-29 23:04
Thanks for the feedback - is this a feature request for this connector to include the formatted values, or is this an error in documentation? 

Tagging @JimDaly in case he has more context.

**Comment by pavansarma93** [comment] 2020-05-06 12:19
@bezhan-msft  1st one is missing feature in latest connector while the 2nd feature suggestion

**Comment by v-aangie** [comment] 2021-08-19 14:47
@pavansarma93 - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 14:47 UTC
Labels: question, open-for-too-long
