### ISSUE TITLE
Additional documentation on managing policy templates needed

### ISSUE THREAD

**Issue by willdrobins** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#86] opened 2020-05-06 21:00 UTC
Is there additional documentation on how to manage policy templates? How do policy templates work across multiple environments? Can they be packaged and deployed in solutions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a9dbfc-59c8-3b66-af5c-7afe0e312384
* Version Independent ID: a34a4759-a955-870c-5566-d2101f0654cb
* Content: [Policy support in custom connectors](https://docs.microsoft.com/en-us/connectors/custom-connectors/policy-templates)
* Content Source: [docs/custom-connectors/policy-templates.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/policy-templates.md)
* Service: **connectors**
* GitHub Login: @shyamsu
* Microsoft Alias: **shyamsu**

**Comment by v-aangie** [comment] 2021-08-19 18:11
@willdrobins - 
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 18:11 UTC
Labels: documentation, doc-request, open-for-too-long
