### ISSUE TITLE
Office 365 seeded licenses - Custom connectors

### ISSUE THREAD

**Issue by DavesTechTips** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#175] opened 2020-08-07 18:03 UTC
Documentation still states that Office 365 seeded licenses are allowed to create custom connectors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a6439e-a119-688b-bb8a-b6fd0b8a37fb
* Version Independent ID: 8250980c-0bd3-6d89-fb0e-24f8ea6eafd8
* Content: [Custom connector FAQ for Azure Logic Apps, Power Automate, and Power Apps](https://docs.microsoft.com/en-us/connectors/custom-connectors/faq)
* Content Source: [docs/custom-connectors/faq.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/faq.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by DougKlopfenstein** [comment] 2020-08-11 21:23
@DavesTechTips Thanks for your feedback.

This issue is being closed because it is a duplicate of issue #159.

**Closed by DougKlopfenstein** 2020-08-11 21:23 UTC
Labels: duplicate
