### ISSUE TITLE
Documentation for "Send Email (V3)" is incomplete/incorrect

### ISSUE THREAD

**Issue by lokijota** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#171] opened 2020-08-02 10:38 UTC
Documentation for "Send Email (V3)" is incomplete/incorrect:

- `Content data`: it says `type` = `byte`, which doesn't make sense (an attatchment's content can't be a single `byte`). Looking at "Send Email [DEPRECATED]" in the same page, this is probably a `string`. Also the description for this field is useless, it just says "Content data". Again the deprecated version is way more useful, it says: "Content data (base64 encoded for streams and as-is for string)".

- `Content id`: no idea what this is supposed to mean. None of the deprecated versions also clarify this. Important to clarify what's expected here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e511d611-347b-aba9-5bc2-139e07a81b20
* Version Independent ID: 9ebdbbaa-06d6-4e36-6036-3da44d7642c8
* Content: [SMTP - Connectors](https://docs.microsoft.com/en-us/connectors/smtpconnector/)
* Content Source: [docs/SMTPConnector/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/SMTPConnector/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment] 2021-08-20 15:23
@lokijota - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-20 15:23 UTC
Labels: doc-request, open-for-too-long
