### ISSUE TITLE
Documentation for deleting webhook

### ISSUE THREAD

**Issue by msjcloud** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#22] opened 2020-03-12 05:54 UTC
Would like to get details of deleting webhook.
What headers are sent along with call? 
What is Authorization header for DELETE call?
Can connector trap this call and send additional headers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0df6a505-f725-a402-da3d-4e400e0f6fc1
* Version Independent ID: fad34bde-59a4-4330-c389-15ce64ac08b8
* Content: [Use a webhook as a trigger for Azure Logic Apps and Power Automate](https://docs.microsoft.com/en-us/connectors/custom-connectors/create-webhook-trigger?source=docs#feedback)
* Content Source: [docs/custom-connectors/create-webhook-trigger.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/create-webhook-trigger.md)
* Service: **flow**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by bezhan-msft** [comment] 2020-03-21 22:35
Thank you for your feedback. This is now under review and no further action is required at this time.

**Comment by bezhan-msft** [comment] 2020-03-21 22:35
https://developer.github.com/v3/repos/hooks/#delete-a-hook

@dougelliott - we may be able to improve our docs using information of the link above.

**Comment by v-aangie** [comment] 2021-08-16 17:27
@msjcloud - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by v-aangie** 2021-08-16 17:27 UTC
Labels: documentation, wontfix, under-review
