### ISSUE TITLE
Link to ASC automation is wrong

### ISSUE THREAD

**Issue by artisticcheese** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#57] opened 2020-04-15 20:27 UTC
https://aka.ms/ASC_WorkflowAutomation is not pointing to Microsoft homepage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 899db6d4-55a7-cd14-13ef-e7fc006cdb41
* Version Independent ID: 2408bf6a-376b-0e8b-8d88-5da1e6e61a2e
* Content: [Security Center Recommendation - Connectors](https://docs.microsoft.com/en-us/connectors/ascassessment/)
* Content Source: [docs/ascassessment/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/ascassessment/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment] 2020-04-29 23:17
Thank you for your feedback. This is now under review and no further action is required at this time.

@ShyamSunder90 - do we know why this link is showing up in the metadata? It doesn't seem to be a field.

**Comment by ShyamSunder90** [comment] 2020-04-30 03:55
@bezhan-msft this is what Security Center Recommendation team has put under externalDoc field in swagger. This property is owned by partner

**Comment by bezhan-msft** [comment] 2020-04-30 17:53
@dougelliott can you please let the partner team know?

**Comment by v-aangie** [comment] 2021-08-18 21:21
@artisticcheese - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by v-aangie** 2021-08-18 21:21 UTC
Labels: bug, open-for-too-long
