### ISSUE TITLE
example to use "Parent object or collection path"

### ISSUE THREAD

**Issue by tannguyen3** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#61] opened 2020-04-20 16:21 UTC
is there any example or reference to what type of path this is? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95493cfc-bc47-9ee3-5015-da6af9edc5b5
* Version Independent ID: c4a2d116-5383-affb-1cbc-2461721ac729
* Content: [Set Property(Preview)](https://docs.microsoft.com/en-us/connectors/custom-connectors/policy-templates/setproperty/setproperty#feedback)
* Content Source: [docs/custom-connectors/policy-templates/setproperty/setproperty.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/policy-templates/setproperty/setproperty.md)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment] 2021-08-18 21:51
@tannguyen3 - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed by v-aangie** 2021-08-18 21:52 UTC
Labels: open-for-too-long
