### ISSUE TITLE
Workday URL format typo

### ISSUE THREAD

**Issue by fraga** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#97] opened 2020-05-13 23:07 UTC
Maybe change following section "Your Workday account endpoint URL (format: https://.workday.com/ccx/service/)" 

to

"Your Workday account endpoint URL (format: https://&lt;DOMAIN&gt;.workday.com/ccx/service/)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f8d788e-44e5-3053-60c0-4331d8ac470c
* Version Independent ID: dc82b995-cd4a-07d8-dcb0-aa7a76017f6a
* Content: [Workday HCM - Connectors](https://docs.microsoft.com/en-us/connectors/workdayhcm/)
* Content Source: [docs/workdayhcm/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/workdayhcm/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment] 2021-08-19 18:39
@fraga - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 18:39 UTC
Labels: doc-request, open-for-too-long
