### ISSUE TITLE
Would be great to have ability to export...

### ISSUE THREAD

**Issue by 4DaddyT** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#75] opened 2020-04-29 16:43 UTC
Would be great to have ability to export this list to Excel, csv, or something....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7741d635-bb14-0cbb-6ddc-d53108b59423
* Version Independent ID: c52d6e84-dc16-af82-9e1f-923659e25c54
* Content: [Connector reference overview](https://docs.microsoft.com/en-us/connectors/connector-reference/#feedback)
* Content Source: [docs/connector-reference/index.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/connector-reference/index.md)
* Service: **connectors**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by bezhan-msft** [comment] 2020-04-29 22:51
I'd like to understand the use cases for this - this list is continuously being updated so it might not be best to take local copies/snapshots. Is the ask to have something similar to an API endpoint for data consumption?

**Comment by steveculshaw** [comment] 2020-05-14 09:10
For me, the export is a secondary requirement. What would be better was a way to subscribe to an update on changes to the list; a new connector, updates on existing connectors, even deprecation of an existing connector

**Comment by 4DaddyT** [comment] 2020-05-14 14:07
We pull and place into a governance doc with have....

**Comment by rootsmusic** [comment] 2021-08-11 20:49
#337 
#203

**Comment by v-aangie** [comment] 2021-08-19 17:43
@4DaddyT - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed by v-aangie** 2021-08-19 17:43 UTC
Labels: question, open-for-too-long
