### ISSUE TITLE
List Resources by Subscription

### ISSUE THREAD

**Issue by DanteNahuel** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#108] opened 2020-05-20 19:49 UTC
It would be great if there was an example on how to use the Advanced options of this Action, like how to filter it by, let's say Resource Type

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d42574e1-1616-a834-454c-0775cfce46fb
* Version Independent ID: 35fd5c8f-fb21-6056-c100-80d418392ddc
* Content: [Azure Resource Manager - Connectors](https://docs.microsoft.com/en-us/connectors/arm/#list-resources-by-subscription)
* Content Source: [docs/ARM/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/ARM/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment] 2021-08-19 18:56
@DanteNahuel - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 18:57 UTC
Labels: doc-request, open-for-too-long
