### ISSUE TITLE
Examples, description connectors for powerplatformforadmins

### ISSUE THREAD

**Issue by fs366e2spm** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#174] opened 2020-08-07 13:27 UTC
Hi,

Could you please provide examples and more description for actions on this page:
https://docs.microsoft.com/en-us/connectors/powerplatformforadmins

Thanks, appreciated.

**Comment by v-aangie** [comment] 2021-08-20 15:32
@fs366e2spm - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed by v-aangie** 2021-08-20 15:32 UTC
Labels: doc-request, open-for-too-long
