### ISSUE TITLE
Freshdesk Connector

### ISSUE THREAD

**Issue by ryanguruconsulting** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#79] opened 2020-05-01 11:41 UTC
Freshdesk connector for action "Create Ticket" is missing key field - "group_id" - cannot create tickets where these field is mandatory. Group_id is an interger. Can be added to the schema please.

**Comment by v-aangie** [comment] 2021-08-19 17:54
@ryanguruconsulting - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed by v-aangie** 2021-08-19 17:54 UTC
Labels: open-for-too-long
