### ISSUE TITLE
App ID Parameter

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#161] opened 2020-07-23 15:49 UTC
[Enter feedback here]
Please provide some information about where we can get the APP ID needed by the Sanction/Unsanction App actions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daec7818-5d63-252b-b338-cdbfe883d644
* Version Independent ID: be170efb-921d-2ac1-0c44-ce1b6b6dff37
* Content: [Cloud App Security - Connectors](https://docs.microsoft.com/en-us/connectors/cloudappsecurity/#tag-app-as-unsanctioned)
* Content Source: [docs/cloudappsecurity/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/cloudappsecurity/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment] 2021-08-19 22:08
@DeanGross - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed by v-aangie** 2021-08-19 22:08 UTC
Labels: doc-request, open-for-too-long
