### ISSUE TITLE
Need more details on how to deal with complex dynamic-values

### ISSUE THREAD

**Issue by nk-gears** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#74] opened 2020-04-29 03:47 UTC
The manual has limited examples on how to work wth ambiguous parameter references when using dynamic values by using the requestBody/id.

But for complex scenarios like array of items, how to resolve the ambiguity to refer the respective property?

In the following case, i am getting this error :

Specified swagger has the following errors: 'Error : paths/~1api~1upload-aws-file~1sheets/post/parameters/2/schema/items/properties/file_content_type/x-ms-dynamic-values/parameters/ext_type/parameter : The parameter could not be found in operation 'UploadProjectSheet' in the swagger document.
'

"parameterReference": "request/file_type"

```
 {
 	"in": "body",
 	"name": "request",
 	"required": true,
 	"schema": {
 		"items": {
 			"properties": {
 				"file_type": {
 					"description": "Type of file you want to upload",
 					"title": "File Type",
 					"type": "string",
 					"x-ms-dynamic-values": {
 						"operationId": "GetMimeTypes",
 						"value-path": "value",
 						"value-title": "name"
 					}
 				},
 				"file_content_type": {
 					"description": "Type of content being uploaded",
 					"title": "Content Type",
 					"type": "string",

 					"x-ms-dynamic-values": {
 						"operationId": "GetMimeByType",
 						"value-path": "mime",
 						"value-title": "extension",
 						"parameters": {
 							"ext_type": {
 								"parameter": "file_type"
 							}
 						}
 					},
 					"x-ms-dynamic-list": {
 						"operationId": "GetMimeByType",
 						"itemValuePath": "mime",
 						"itemTitlePath": "extension",
 						"parameters": {
 							"ext_type": {
 								"parameterReference": "request/file_type"
 							}
 						}
 					}

 				}

 			}
 		}
 	}

 }


```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a56ded11-62f2-5eb0-e311-19d9476eca39
* Version Independent ID: 95c07373-f2af-8561-828a-0bb3fd2a775b
* Content: [Extend an OpenAPI definition for a custom connector](https://docs.microsoft.com/en-us/connectors/custom-connectors/openapi-extensions#feedback)
* Content Source: [docs/custom-connectors/openapi-extensions.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/openapi-extensions.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by v-aangie** [comment] 2021-08-19 17:40
@nk-gears - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 17:41 UTC
Labels: open-for-too-long
