### ISSUE TITLE
Need to specify the API version used by the Salesforce connectors

### ISSUE THREAD

**Issue by goravseth** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#123] opened 2020-06-05 17:33 UTC
I am building a flow and am looking to leverage an opportunity field released in Salesforce API 46, and its not visible in my flow.  

I assume that the connector is running on an older api version, but this should be clearly specified in the documentation so that I dont need to log a support ticket.  Also it would be good to be transparent about the protocols for updating the API version on the connectors, so we can build with that in mind.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1edb85cd-28f3-bc48-8ba9-bebc6382ae56
* Version Independent ID: d634090e-3bc4-631e-9493-9be296ca0194
* Content: [Salesforce - Connectors](https://docs.microsoft.com/en-us/connectors/salesforce/)
* Content Source: [docs/Salesforce/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Salesforce/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment] 2021-08-19 19:20
@goravseth - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed by v-aangie** 2021-08-19 19:20 UTC
Labels: doc-request, open-for-too-long
