### ISSUE TITLE
Office 365 Groups Rebranding to Microsoft 365 Groups

### ISSUE THREAD

**Issue by rarajase** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#113] opened 2020-05-27 01:14 UTC
Hi,
All references to Office 365 Group(s) should be changed to Microsoft 365 Group(s). Please refer to spec doc here: https://microsoft.sharepoint.com/:w:/t/GroupsTeam/EYxSoeR6IKhGpve2mOCaDD0B_FRyLizhpjJH6DejqeouSg?e=FD9ANZ

Please reach out to rarajase@microsoft.com for questions. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66d136b3-75bc-fd53-2d17-15f0904a0b54
* Version Independent ID: 71609855-7cb2-9994-e8f3-13fe93d9aa54
* Content: [Office 365 Groups - Connectors](https://docs.microsoft.com/en-us/connectors/office365groups/#feedback)
* Content Source: [docs/office365groups/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/office365groups/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by DougKlopfenstein** [comment] 2020-08-12 16:37
Duplicate of #139

**Closed by DougKlopfenstein** 2020-08-12 16:37 UTC
Labels: duplicate
