### ISSUE TITLE
HTTP connector not documented in list

### ISSUE THREAD

**Issue by mirlenbrink** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#149] opened 2020-07-08 17:50 UTC
The HTTP connector is not listed in the full list of all connectors.  'HTTP with Azure AD' is documented/listed but not the regular HTTP connector.

**Comment by DougKlopfenstein** [comment] 2020-07-13 18:56
@mirlenbrink Thanks for your feedback.

Closing because this is a duplicate of [#101](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors-public/issues/101).

**Closed** 2020-07-13 18:56 UTC
