### ISSUE TITLE
Token and server instance

### ISSUE THREAD

**Issue by MrVincs** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#40] opened 2020-04-03 08:47 UTC
Hi team,

Can you please provide documentation for the Server version of Jira  (or DataCenter) without Atlassian ID (and so without Token generation) ?

In our case we use Crowd as SSO, how i can made connection between them ?
Can i simple use the service account password in the 'token' field ?

Thank you,
-- Vincent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76d2c23e-c66c-3e66-f61d-681c4327e461
* Version Independent ID: 0c4a4d9e-d055-d56e-6b48-c70cb753aa60
* Content: [JIRA - Connectors](https://docs.microsoft.com/en-us/connectors/jira/#feedback)
* Content Source: [docs/JIRA/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/JIRA/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by hananeseo** [comment] 2020-04-14 12:19
Same question for me. Thank you,

**Comment by MrVincs** [comment] 2020-04-14 12:39
Hi @hananeseo,

After test, you can simply use plein text password on Token field :)

Ps: I think the call is simply REST call with Basic header, so token or password is the same think.

=> But the doc already need update for this information.

**Comment by bezhan-msft** [comment] 2020-04-29 23:37
Thank you for your feedback. This is now under review and no further action is required at this time.

**Comment by shutchinson** [comment] 2020-05-08 14:27
ALso wondering how this can be used with JIRA Server as it does not seem to have API tokens.

**Comment by v-aangie** [comment] 2021-08-18 20:22
@MrVincs - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by v-aangie** 2021-08-18 20:22 UTC
Labels: under-review, open-for-too-long
