### ISSUE TITLE
Has this connector been renamed?

### ISSUE THREAD

**Issue by devlinl** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#177] opened 2020-08-13 21:06 UTC
In building a flow, I no longer see "Common Data Service (current enviornment)". Instead I see "Dataflex (Common Data Service current).

Is Dataflex now the correct connector to be using?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78bf3518-bce4-ecc5-8bf6-1fb627b9105e
* Version Independent ID: d46568f2-e080-cbbe-2f7e-a655bce20b64
* Content: [Common Data Service (current environment) - Connectors](https://docs.microsoft.com/en-us/connectors/commondataserviceforapps/)
* Content Source: [docs/commondataserviceforapps/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/commondataserviceforapps/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment] 2021-08-20 15:18
@devlinl - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed by v-aangie** 2021-08-20 15:18 UTC
Labels: open-for-too-long
