### ISSUE TITLE
Get Items Top Count

### ISSUE THREAD

**Issue by bblasingame** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#77] opened 2020-04-30 14:56 UTC
In the Get Items Control I think the Default for Top Count is 100 not All Items. I have read that else where and discovered this in practice. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69a01872-3062-4100-f807-7d43e8111e9f
* Version Independent ID: 48560378-76ed-cb42-e816-894179e1f16d
* Content: [SharePoint - Connectors](https://docs.microsoft.com/en-us/connectors/sharepointonline/#update-item)
* Content Source: [docs/sharepointonline/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/sharepointonline/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by khkh1919** [comment] 2020-04-30 16:53
I can confirm we are also experiencing this issue in our tenant. The help text says "default=all" but if that field is left blank, only 100 items will be read. So either the help text needs to be fixed, or the 100 default needs to be changed for all.

![image](https://user-images.githubusercontent.com/64604841/80737413-74331180-8ae1-11ea-9329-33a17e800789.png)

**Comment by v-aangie** [comment] 2021-08-19 17:49
@bblasingame - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed by v-aangie** 2021-08-19 17:50 UTC
Labels: open-for-too-long
