### ISSUE TITLE
"Add azure.apim as one of the authorized domains" doesn't work

### ISSUE THREAD

**Issue by garethmoores** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#143] opened 2020-07-01 10:42 UTC
"Add azure.apim as one of the authorized domains."

This instruction doesn't work for me. I think I got it to work using "azure-apim.net" instead. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94336520-0566-edeb-a3c8-48e7065c19b2
* Version Independent ID: aec0952b-45bb-6d5c-532f-9e3451713e98
* Content: [Gmail - Connectors](https://docs.microsoft.com/en-au/connectors/gmail/#creating-an-oauth-client-application-in-google)
* Content Source: [docs/Gmail/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Gmail/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment] 2021-08-19 20:25
@garethmoores - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 20:25 UTC
Labels: doc-request, open-for-too-long
