### ISSUE TITLE
MailChimp connector : "Add member to list" Action doesn't work when updating an existing member of a list

### ISSUE THREAD

**Issue by DForlen** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#69] opened 2020-04-27 15:12 UTC
The "Add member to list" Action doesn't work when updating an existing member of a list. Whereas the documentation (https://docs.microsoft.com/fr-fr/connectors/mailchimp/#add-member-to-list) describes this action with the following : "Add or **update** a list member"

If the member exists, it returns the following error : 

{
  "type": "http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/",
  "title": "Member Exists",
  "status": 400,
  "detail": "MAIL@ADDRESS.COM is already a list member. Use PUT to insert or update list members."
}

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 765ffd53-c328-ee9f-f577-6889c528ef99
* Version Independent ID: d93a62f2-735d-4597-aa1b-ad8c8c5976de
* Content: [MailChimp - Connectors](https://docs.microsoft.com/fr-fr/connectors/mailchimp/)
* Content Source: [docs/MailChimp/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/MailChimp/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment] 2020-04-29 23:00
Thank you for your feedback. This is now under review and no further action is required at this time.

**Comment by v-aangie** [comment] 2021-08-19 17:37
@DForlen - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 17:38 UTC
Labels: bug, documentation, under-review, open-for-too-long
