### ISSUE TITLE
Fix link to create custom connector from a postman collection

### ISSUE THREAD

**Issue by sntnupl** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#147] opened 2020-07-08 05:03 UTC
In this document the link to "Create a custom connector from a Postman collection" points to URL: "https://docs.microsoft.com/en-us/connectors/custom-connectors/define-blank"

This should point to URL: "https://docs.microsoft.com/en-us/connectors/custom-connectors/define-postman-collection" instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c443c1c-e4af-1f21-10b3-9c8d81abc1f1
* Version Independent ID: 9aa14809-3da3-23b3-3210-7a2e84608f04
* Content: [Create a custom connector from scratch](https://docs.microsoft.com/en-us/connectors/custom-connectors/define-blank)
* Content Source: [docs/custom-connectors/define-blank.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/define-blank.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by DougKlopfenstein** [comment] 2020-07-13 17:02
@sntnupl Duplicate of #127. Closing.

**Closed by DougKlopfenstein** 2020-07-13 17:02 UTC
Labels: duplicate
