### ISSUE TITLE
Title is confusing

### ISSUE THREAD

**Issue by vnextcoder** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#145] opened 2020-07-05 05:07 UTC
[Enter feedback here]

this should be named as Using Customer Connectors in a Logic App

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7187da26-8713-2b7d-6619-85f0ff408539
* Version Independent ID: 8ba5cb60-c3fa-06e6-d966-ffd5956ed66e
* Content: [Use a custom connector from a logic app](https://docs.microsoft.com/en-us/connectors/custom-connectors/use-custom-connector-logic-apps)
* Content Source: [docs/custom-connectors/use-custom-connector-logic-apps.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/use-custom-connector-logic-apps.md)
* Service: **connectors**
* GitHub Login: @divyaswarnkar
* Microsoft Alias: **divswa**

**Comment by v-aangie** [comment] 2021-08-19 20:27
@vnextcoder - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 20:27 UTC
Labels: open-for-too-long

**Comment by vnextcoder** [comment] 2021-08-21 05:50
The Title is fixed already earlier :)
