### ISSUE TITLE
Preview & Premium icons are not visible in dark mode

### ISSUE THREAD

**Issue by ghurlman** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#59] opened 2020-04-17 19:08 UTC
When the docs site is set to dark mode, the preview and premium connector icons appear blank:

![Screen clipping of the page with Docs in dark mode](https://i.imgur.com/JwWzvCT.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7741d635-bb14-0cbb-6ddc-d53108b59423
* Version Independent ID: c52d6e84-dc16-af82-9e1f-923659e25c54
* Content: [Connector reference overview](https://docs.microsoft.com/en-us/connectors/connector-reference/)
* Content Source: [docs/connector-reference/index.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/connector-reference/index.md)
* Service: **connectors**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by bezhan-msft** [comment] 2020-04-17 23:03
Thank you for your feedback. This is a **known issue**, now under review and no further action is required at this time.

**Comment by v-aangie** [comment] 2021-08-18 21:46
@ghurlman - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed by v-aangie** 2021-08-18 21:46 UTC
Labels: bug, under-review, high-priority, open-for-too-long
