### ISSUE TITLE
OData Filters

### ISSUE THREAD

**Issue by buildbod** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#126] opened 2020-06-10 09:55 UTC
Several of the Shifts Connectors e.g. List all open shift requests are not useable as they do not include the ability to filter to a specific time range. They return values from the start of the schedule and the greater the time elapsed from the start of the schedule the greater the number of items returned with the result that the Connector reaches a theshold and fails to return all items.

Being able to focus on a specific time frame, as is the case with connectors like List Shifts would focus the response 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb4ba692-98a2-2ec7-319b-d75b59d3fa50
* Version Independent ID: c24a9495-e4cb-28db-3657-ecf81005757b
* Content: [Microsoft Teams - Connectors](https://docs.microsoft.com/en-gb/connectors/teams/#shifts%3a-list-all-open-shift-requests)
* Content Source: [docs/Teams/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Teams/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment] 2021-08-19 19:21
@buildbod - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 19:21 UTC
Labels: open-for-too-long
