### ISSUE TITLE
Description for Custom connector FAQ out of date

### ISSUE THREAD

**Issue by shion2333** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#159] opened 2020-07-20 05:27 UTC
The name of plans below seems to be out of date.
Office 365 -> Microsoft 365
Plan 1 and Plan 2 -> Power Automate per user plan and Power Automate per flow plan?

https://docs.microsoft.com/en-us/connectors/custom-connectors/faq#limits

Power Automate and Power Apps | Limit
-- | --
Number of custom connectors that you can create | Free plan: one <br>Office 365 and Dynamics 365 plans: one <br>Plan 1 and Plan 2: unlimited

Reference:
https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq#what-will-happen-to-the-power-apps-p1p2-and-power-automate-plan-1-and-plan-2-plans-on-october-1-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a6439e-a119-688b-bb8a-b6fd0b8a37fb
* Version Independent ID: 8250980c-0bd3-6d89-fb0e-24f8ea6eafd8
* Content: [Custom connector FAQ for Azure Logic Apps, Power Automate, and Power Apps](https://docs.microsoft.com/en-us/connectors/custom-connectors/faq)
* Content Source: [docs/custom-connectors/faq.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/faq.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by v-aangie** [comment] 2021-08-19 22:04
@shion2333 - 
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 22:04 UTC
Labels: documentation, doc-request, open-for-too-long
