### ISSUE TITLE
Please change all references to Office 365 Groups to Microsoft 365 Groups

### ISSUE THREAD

**Issue by rarajase** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#139] opened 2020-06-24 16:26 UTC
[Enter feedback here]

Please change all references to Office 365 Groups to Microsoft 365 Groups
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66d136b3-75bc-fd53-2d17-15f0904a0b54
* Version Independent ID: 71609855-7cb2-9994-e8f3-13fe93d9aa54
* Content: [Office 365 Groups - Connectors](https://docs.microsoft.com/en-us/connectors/office365groups/)
* Content Source: [docs/office365groups/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/office365groups/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment] 2020-08-11 23:07
Thank you for your feedback - we are working on a friendly experience for end users with partner teams to conduct this change as it's not as simple as changing the connector name.

**Comment by v-aangie** [comment] 2021-08-19 20:22
@rarajase - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed by v-aangie** 2021-08-19 20:22 UTC
Labels: documentation, high-priority, open-for-too-long
