### ISSUE TITLE
Does the 1024 contacts limitation apply to all versions of "Get my contacts" through v4?

### ISSUE THREAD

**Issue by LarsKemmann** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#84] opened 2020-05-06 13:55 UTC
The limitations section states:

> Action "Get my contacts" currently does not support pagination. It returns 1024 contacts maximum. If you have more contacts, only first 1024 will be returned back by the action.

Does that apply to every version of "Get my contacts" (v1 through v4 which is currently the newest), or only to v1?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c842ceb7-14c0-8889-06a8-4ea116bd2f7e
* Version Independent ID: 9424248f-bec3-7fdc-f4f4-01ac1d5d7d2f
* Content: [Google Contacts - Connectors](https://docs.microsoft.com/en-us/connectors/googlecontacts/#get-my-contacts-v4)
* Content Source: [docs/GoogleContacts/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/GoogleContacts/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment] 2021-08-19 18:06
@LarsKemmann - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed by v-aangie** 2021-08-19 18:06 UTC
Labels: open-for-too-long
