### ISSUE TITLE
Excel Online (Business) not available in PowerApps

### ISSUE THREAD

**Issue by NK-debug** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#66] opened 2020-04-24 13:48 UTC
The Excel Online (Business) connector is only available in Microsoft Flow/Automate, not PowerApps (4/2020).
Please indicate that in the docs here so that people don't keep looking for it.
Better yet, make it available in PowerApps too.
Because not everybody wants to use an Excel file in OneDrive; sometimes the Excel file is in SharePoint.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63dd2d5e-d90f-4654-c406-256e3e680e6d
* Version Independent ID: f2cd384b-2690-393d-3058-a363523f7d62
* Content: [Excel Online (Business) - Connectors](https://docs.microsoft.com/en-us/connectors/excelonlinebusiness/#feedback)
* Content Source: [docs/excelonlinebusiness/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/excelonlinebusiness/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment] 2020-04-29 23:02
Hello, in the documentation at the top under "This connector is available in the following products and regions:" - I don't see it saying it's available in Power Apps. 

Could you please clarify where you are seeing the error?

**Comment by NK-debug** [comment] 2020-04-29 23:24
The request was for an explicit statement that the connector is not available in PowerApps.
Because the bottom of that page has these URLs that include "Power Apps":
"Contact	
Name	Microsoft
URL	Microsoft Power Automate Support
	Microsoft Power Apps Support"

And if a PowerApp developer does a search for Excel connectors, this list of connectors comes up in the Microsoft docs:
"Excel
Excel Online (Business)
Excel Online (OneDrive)"

The first is deprecated. The last works with PowerApps, but only if the Excel file is in OneDrive, not SharePoint.

**Comment by bezhan-msft** [comment] 2020-04-30 18:20
Thank you for reporting this issue - it makes sense that a "Microsoft Power Apps Support" link should not be provided for a connector not available in Power Apps. We have filed a bug and are working on a fix. 

We generally do not call out specific products or regions a connector is not available in, as we use the aforementioned table of availability for that.

Lastly, we have filters under the Connector Reference in the Table of Contents for viewing a list of connectors available in a specific product.

**Comment by SnehalTajave** [comment] 2021-06-25 10:14
Customer is able to add the Excel online business connector when he creates new canvas app. 
However connector is not available when he is trying to import app through solution and trying to add mentioned data source.
![image](https://user-images.githubusercontent.com/86424617/123409750-2d00bd80-d5cc-11eb-9c06-ed4d5edb78cd.png)

**Comment by v-aangie** [comment] 2021-08-19 17:33
@NK-debug - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 17:34 UTC
Labels: under-review, open-for-too-long
