### ISSUE TITLE
CalendarDeleteItem_V2 function gives error in Power Apps

### ISSUE THREAD

**Issue by hkmamun** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#45] opened 2020-04-06 21:13 UTC
I have used this function in below way, but it given error in Power Apps
Office365Outlook.CalendarDeleteItem_V2(
"Calendar",
EventID);

but if I use CalendarDeleteItemV2 instead of CalendarDeleteItem_V2 then it gives no error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc40a098-af8c-d8a9-4538-71d184efbe91
* Version Independent ID: 0ee8cf79-18e9-d923-607f-ef40cdd23e4d
* Content: [Office 365 Outlook - Connectors](https://docs.microsoft.com/en-us/connectors/office365/#delete-event-(v2))
* Content Source: [docs/office365/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/office365/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment] 2020-04-29 23:42
Hello, where do you see CalendarDeleteItemV2?

**Comment by hkmamun** [comment] 2020-05-02 14:48
I have used Office365Outlook.CalendarDeleteItem_V2() thsi function and got error but if I use Office365Outlook.CalendarDeleteItemV2() function then no error.

**Comment by v-aangie** [comment] 2021-08-18 20:32
@hkmamun - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by v-aangie** 2021-08-18 20:32 UTC
Labels: question, open-for-too-long
