### ISSUE TITLE
Is this still valid doc?

### ISSUE THREAD

**Issue by tgn12** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#78] opened 2020-04-30 18:57 UTC
I couldn't find the SOAP option in the custom connector anymore

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5a468c0-ab8f-07b7-6666-6ffa98781277
* Version Independent ID: b70a7642-5968-1c43-cfbb-d09695c40c28
* Content: [Create and register a SOAP custom connector in Azure Logic Apps](https://docs.microsoft.com/en-us/connectors/custom-connectors/create-register-logic-apps-soap-connector)
* Content Source: [docs/custom-connectors/create-register-logic-apps-soap-connector.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/create-register-logic-apps-soap-connector.md)
* Service: **connectors**
* GitHub Login: @divyaswarnkar
* Microsoft Alias: **divswa**

**Comment by aljawad** [comment] 2020-05-07 06:43
I can't see SOAP option too!

**Comment by v-aangie** [comment] 2021-08-19 17:52
@tgn12 - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed by v-aangie** 2021-08-19 17:52 UTC
Labels: open-for-too-long
