### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by madenwala** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#13] opened 2020-03-03 18:36 UTC
Portal has changed, please update instructions/images

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e584c228-236a-27fd-52b6-0910a7e67a13
* Version Independent ID: ec7aceaf-0855-b0c0-3468-9030e339a607
* Content: [Authenticate your API and connector with Azure Active Directory - Azure AD](https://docs.microsoft.com/en-us/connectors/custom-connectors/azure-active-directory-authentication)
* Content Source: [docs/custom-connectors/azure-active-directory-authentication.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/azure-active-directory-authentication.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by v-aangie** [comment] 2021-08-16 17:25
@madenwala - 
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by v-aangie** 2021-08-16 17:25 UTC
Labels: wontfix, under-review
