### ISSUE TITLE
Can't add azure.apim as Authorised domains on oAuth consent screen

### ISSUE THREAD

**Issue by e14mattc** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#82] opened 2020-05-05 16:25 UTC
Following the instructions for 'Bring your own application' and adding 'azure.apim' as per the instructions gives an error saying 'Invalid domain: must be a top private domain.'

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94336520-0566-edeb-a3c8-48e7065c19b2
* Version Independent ID: aec0952b-45bb-6d5c-532f-9e3451713e98
* Content: [Gmail - Connectors](https://docs.microsoft.com/en-gb/connectors/gmail/#feedback)
* Content Source: [docs/Gmail/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Gmail/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by NabeelSalie** [comment] 2020-05-19 09:16
Receiving the same issue as above

**Comment by bezhan-msft** [comment] 2020-07-07 20:18
@schabungbam for this issue.

**Comment by v-aangie** [comment] 2021-08-19 18:00
@e14mattc - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 18:01 UTC
Labels: under-review, open-for-too-long
