### ISSUE TITLE
Support of complex paths in "value-collection" of "x-ms-dynamic-values"

### ISSUE THREAD

**Issue by wilecoyotegenius** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#153] opened 2020-07-09 15:24 UTC
Documentation says that "value-collection" parameter is "a path string". However when value of this parameter points to a more complex path (i.e.: "data/elements"), dynamic values are not getting listed in editor. 
Is this a bug in Power Automate flow editor, or is there a strict limitation to "value-collection" parameter not to be complex path? If the latter, it should be clearly mentioned in documentation (I could not find any official statement about this).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a56ded11-62f2-5eb0-e311-19d9476eca39
* Version Independent ID: 95c07373-f2af-8561-828a-0bb3fd2a775b
* Content: [Extend an OpenAPI definition for a custom connector](https://docs.microsoft.com/en-us/connectors/custom-connectors/openapi-extensions#use-dynamic-values)
* Content Source: [docs/custom-connectors/openapi-extensions.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/openapi-extensions.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by v-aangie** [comment] 2021-08-19 20:50
@wilecoyotegenius - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed** 2021-08-19 21:08 UTC
Labels: documentation, doc-request, open-for-too-long

**Comment by rvermaquark** [comment] 2023-10-05 07:56
Hey i am having trouble getting root elements using value-collection from a response to populate the dropdown list.
{
    "A": [
        "awdwad",
        "awdawd"
    ],
    "B": [
        "fefa",
        "rawdawdr"
    ]
}

I want A, B in dropdown using x-ms-dynamic-values, is this possible, I know the issue is close but still wanted to leave it here.
