### ISSUE TITLE
Visual jarring between the main icon graphic and the availability glyphs

### ISSUE THREAD

**Issue by steveculshaw** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#98] opened 2020-05-14 09:07 UTC
Excellent resource.

It's really useful to be able to filter ... one nice extra would be filter for ISE variant here

One negative ... I find the small glyphs indicating the availability visually jarring with the main icon for the connector

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7741d635-bb14-0cbb-6ddc-d53108b59423
* Version Independent ID: c52d6e84-dc16-af82-9e1f-923659e25c54
* Content: [Connector reference overview](https://docs.microsoft.com/en-gb/connectors/connector-reference/)
* Content Source: [docs/connector-reference/index.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/connector-reference/index.md)
* Service: **connectors**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by v-aangie** [comment] 2021-08-19 18:41
@steveculshaw - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue in one of the forums listed here - https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.

**Closed by v-aangie** 2021-08-19 18:41 UTC
Labels: doc-request, open-for-too-long
